### ISSUE TITLE
Download missing for 1.7.10 for Death Chest v1.0.1 for Minecraft 1.72/1.7.10

### ISSUE THREAD

**Issue by ProsperCraft** [Tyler1555/Death-Chest#1]

**Comment by hunterwoo** [comment]
I wanna ask for this question also, can you give us the jar pack Tyler?

**Comment by Tyler1555** [comment]
I'll do my best to get a build up by today

**Comment by hunterwoo** [comment]
thank you very much

**Comment by hunterwoo** [comment]
If you're too busy, I read your source code of v1.0.1, quite different from the v1.0 source code, is this source code fixed the bug that would cause loss of items? if true, I can seek for some help by my programmer friend to make the jar pack:)

**Comment by Tyler1555** [comment]
Sorry, got a bit busy and forgot about this. Gradle is having a hard time setting up the build environment so I'll give a crack at it tomorrow.

**Comment by jedipeludo** [comment]
Any news yet?

**Comment by jedipeludo** [comment]
Hey if anyone is looking for the 1.7.10 release please go to:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294366-1-8-1-7-x-ssp-smp-forge-death-chest-climbin-in-yo?comment=68

It even got updated.

**Comment by Tyler1555** [comment]
Thanks!
